[workspace]
members = ["."]

[workspace.package]
version = "0.0.0"
edition = "2021"

[workspace.dependencies]
soroban-sdk = "27.0.6"

[package]
name = "autopilot-vault"
version.workspace = true
edition.workspace = true
publish = false

[lib]
crate-type = ["lib", "cdylib"]
doctest = false

[dependencies]
soroban-sdk = { workspace = true }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
